# Generated by Django 4.0.2 on 2022-02-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
